
// This file was generated by a tool. 
// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated. 
//var docNum = document.getElementById("Data_Invoices_DocumentNumber").value;
//get username
//declare ip address
//var ipAddress = "10.1.0.4:1992"
var ipAddress = "REPLACEME";

var loggedInUser = document.getElementById("Data_Invoices_EnteredBy").value;
var docNum = document.getElementById("Data_Invoices_DocumentNumber").value;


//get live doc nr
function getTransDetails () {
    docNum = document.getElementById("Data_Invoices_DocumentNumber").value;
    docNum.toUpperCase();
}
//eventlistener for inv number
var obtainDocDetails = document.getElementById("Data_Invoices_DocumentNumber");
obtainDocDetails.addEventListener("keyup", getTransDetails, false);

//build link
$("#Button1").click(function () {
    docNum = document.getElementById("Data_Invoices_DocumentNumber").value;
    var ZDOCURL = "http://" + ipAddress + "/EDMS%20Web%20Integration.aspx?DocumentNo=" + docNum + "&Screencode=Sales&Username=" + loggedInUser;
    //"http:// 10.1.0.4:1992/EDMS%20Web%20Integration.aspx?DocumentNo=SAINV0110006&Screencode=Sales&Username=ADMIN" 
    window.open(ZDOCURL, null,
        "height=600,width=1100,left=120,top=40,resizable=yes,status=yes,toolbar=no,menubar=no,location=no");
});

"use strict";

var LinkTestAPInvoiceEntryCustomizationUI = LinkTestAPInvoiceEntryCustomizationUI || {};
var LinkTestAPInvoiceEntrycustomizationViewModel;

LinkTestAPInvoiceEntryCustomizationUI = {

    // Init
    init: function () {
        LinkTestAPInvoiceEntryCustomizationUI.initIntercept();
        LinkTestAPInvoiceEntryCustomizationUI.initAjaxCallIntercept();
        LinkTestAPInvoiceEntryCustomizationUI.initButtons();
        LinkTestAPInvoiceEntryCustomizationUI.initFinders();
        LinkTestAPInvoiceEntryCustomizationUI.initTextbox();
        LinkTestAPInvoiceEntryCustomizationUI.initNumericTextBox();
        LinkTestAPInvoiceEntryCustomizationUI.initDropDownList();
        LinkTestAPInvoiceEntryCustomizationUI.initDatePicker();
        LinkTestAPInvoiceEntryCustomizationUI.initCheckBoxes();
        LinkTestAPInvoiceEntryCustomizationUI.initGrid();
        LinkTestAPInvoiceEntryCustomizationUI.initOtherControls();
    },

    //Hijack and intercept events, before the event
    initIntercept: function () {
    },

    //Intercept before/after Ajax calls
    initAjaxCallIntercept: function () {

        $(document).ajaxSend(function (event, jqxhr, settings) {
        });

        $(document).ajaxSuccess(function (event, xhr, settings) {
        });

    },

    // Init Buttons
    initButtons: function () {
    },

    // Init TextBoxs
    initTextbox: function(){
    },

    // Init Numeric TextBox
    initNumericTextBox: function () {
    },

    // Init Dropdown List
    initDropDownList: function () {
    },

    // Init Date Picker
    initDatePicker: function() {
        //$("#dtPickerCustom").kendoDatePicker({});
    },

    // Init Sage 300 Finders
    initFinders: function () {
        //sg.finderHelper.setFinder("btnCustomCurrencyFinder", sg.finder.TaxCurrencyFinder, LinkTestAPInvoiceEntryCustomizationUICallback.currencyCode, null, "Customization Currency Finder", sg.finderHelper.createDefaultFunction("txtCustomCurrency", "CurrencyCodeId", sg.finderOperator.StartsWith), null, true);
    },

    //Init CheckBoxs
    initCheckBoxes: function () {
    },

    //Init kendo Grid
    initGrid: function () {
    },

    //Init Other type controls
    initOtherControls: function () {
    },

};


var LinkTestAPInvoiceEntryCustomizationUICallback = {
};

// Initial Entry
$(function () {
    LinkTestAPInvoiceEntryCustomizationUI.init();
});
