
// This file was generated by a tool. 
// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated. 

// //declare ip address
// //var ipAddress = "10.1.0.4:1992"
var ipAddress = "REPLACEME";
// //get username + document number
// loggedInUser = Data_Invoices_EnteredBy.value;
apCustNum = Data_CustomerNumber.value;
apCustNum = apCustNum.toUpperCase();

//get live document number
$("#Data_CustomerNumber").keyup(function () {
    apCustNum = Data_CustomerNumber.value;
    apCustNum = apCustNum.toUpperCase();
});

//build link
$("#ARCustDocumentAttachButton").click(function () {
    ////loggedInUser = Data_Invoices_EnteredBy.value;
    apCustNum = Data_CustomerNumber.value;
    apCustNum = apCustNum.toUpperCase();
    var ZDOCURL = "http://" + ipAddress + "/EDMS%20Web%20Integration.aspx?DocumentNo=" + apCustNum + "&Screencode=Customer&Username=ADMIN";
    //"http:// 10.1.0.4:1992/EDMS%20Web%20Integration.aspx?DocumentNo=SAINV0110006&Screencode=Sales&Username=ADMIN" 
    window.open(ZDOCURL, null,
        "height=600,width=1100,left=120,top=40,resizable=yes,status=yes,toolbar=no,menubar=no,location=no");
});

"use strict";

var AcctechSystemsCustomerCustomizationUI = AcctechSystemsCustomerCustomizationUI || {};
var AcctechSystemsCustomercustomizationViewModel;

AcctechSystemsCustomerCustomizationUI = {

    // Init
    init: function () {
        AcctechSystemsCustomerCustomizationUI.initIntercept();
        AcctechSystemsCustomerCustomizationUI.initAjaxCallIntercept();
        AcctechSystemsCustomerCustomizationUI.initButtons();
        AcctechSystemsCustomerCustomizationUI.initFinders();
        AcctechSystemsCustomerCustomizationUI.initTextbox();
        AcctechSystemsCustomerCustomizationUI.initNumericTextBox();
        AcctechSystemsCustomerCustomizationUI.initDropDownList();
        AcctechSystemsCustomerCustomizationUI.initDatePicker();
        AcctechSystemsCustomerCustomizationUI.initCheckBoxes();
        AcctechSystemsCustomerCustomizationUI.initGrid();
        AcctechSystemsCustomerCustomizationUI.initOtherControls();
    },

    //Hijack and intercept events, before the event
    initIntercept: function () {
    },

    //Intercept before/after Ajax calls
    initAjaxCallIntercept: function () {

        $(document).ajaxSend(function (event, jqxhr, settings) {
        });

        $(document).ajaxSuccess(function (event, xhr, settings) {
        });

    },

    // Init Buttons
    initButtons: function () {
    },

    // Init TextBoxs
    initTextbox: function(){
    },

    // Init Numeric TextBox
    initNumericTextBox: function () {
    },

    // Init Dropdown List
    initDropDownList: function () {
    },

    // Init Date Picker
    initDatePicker: function() {
        //$("#dtPickerCustom").kendoDatePicker({});
    },

    // Init Sage 300 Finders
    initFinders: function () {
        //sg.finderHelper.setFinder("btnCustomCurrencyFinder", sg.finder.TaxCurrencyFinder, AcctechSystemsCustomerCustomizationUICallback.currencyCode, null, "Customization Currency Finder", sg.finderHelper.createDefaultFunction("txtCustomCurrency", "CurrencyCodeId", sg.finderOperator.StartsWith), null, true);
    },

    //Init CheckBoxs
    initCheckBoxes: function () {
    },

    //Init kendo Grid
    initGrid: function () {
    },

    //Init Other type controls
    initOtherControls: function () {
    },

};


var AcctechSystemsCustomerCustomizationUICallback = {
};

// Initial Entry
$(function () {
    AcctechSystemsCustomerCustomizationUI.init();
});
