
// This file was generated by a tool. 
// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated. 

// //declare ip address
// //var ipAddress = "10.1.0.4:1992"
var ipAddress = "REPLACEME";
// //get username + document number
// loggedInUser = Data_Invoices_EnteredBy.value;
apVenNum = Data_VendorNumber.value;
apVenNum = apVenNum.toUpperCase();

//get live document number
$("#Data_VendorNumber").keyup(function () {
    apVenNum = Data_VendorNumber.value;
    apVenNum = apVenNum.toUpperCase();
});

//build link
$("#APVenDocumentAttachButton").click(function () {
    ////loggedInUser = Data_Invoices_EnteredBy.value;
    apVenNum = Data_VendorNumber.value;
    apVenNum = apVenNum.toUpperCase();
    var ZDOCURL = "http://" + ipAddress + "/EDMS%20Web%20Integration.aspx?DocumentNo=" + apVenNum + "&Screencode=Supplier&Username=ADMIN";
    //"http:// 10.1.0.4:1992/EDMS%20Web%20Integration.aspx?DocumentNo=SAINV0110006&Screencode=Sales&Username=ADMIN" 
    window.open(ZDOCURL, null,
        "height=600,width=1100,left=120,top=40,resizable=yes,status=yes,toolbar=no,menubar=no,location=no");
});

"use strict";

var AcctechSystemsVendorCustomizationUI = AcctechSystemsVendorCustomizationUI || {};
var AcctechSystemsVendorcustomizationViewModel;

AcctechSystemsVendorCustomizationUI = {

    // Init
    init: function () {
        AcctechSystemsVendorCustomizationUI.initIntercept();
        AcctechSystemsVendorCustomizationUI.initAjaxCallIntercept();
        AcctechSystemsVendorCustomizationUI.initButtons();
        AcctechSystemsVendorCustomizationUI.initFinders();
        AcctechSystemsVendorCustomizationUI.initTextbox();
        AcctechSystemsVendorCustomizationUI.initNumericTextBox();
        AcctechSystemsVendorCustomizationUI.initDropDownList();
        AcctechSystemsVendorCustomizationUI.initDatePicker();
        AcctechSystemsVendorCustomizationUI.initCheckBoxes();
        AcctechSystemsVendorCustomizationUI.initGrid();
        AcctechSystemsVendorCustomizationUI.initOtherControls();
    },

    //Hijack and intercept events, before the event
    initIntercept: function () {
    },

    //Intercept before/after Ajax calls
    initAjaxCallIntercept: function () {

        $(document).ajaxSend(function (event, jqxhr, settings) {
        });

        $(document).ajaxSuccess(function (event, xhr, settings) {
        });

    },

    // Init Buttons
    initButtons: function () {
    },

    // Init TextBoxs
    initTextbox: function(){
    },

    // Init Numeric TextBox
    initNumericTextBox: function () {
    },

    // Init Dropdown List
    initDropDownList: function () {
    },

    // Init Date Picker
    initDatePicker: function() {
        //$("#dtPickerCustom").kendoDatePicker({});
    },

    // Init Sage 300 Finders
    initFinders: function () {
        //sg.finderHelper.setFinder("btnCustomCurrencyFinder", sg.finder.TaxCurrencyFinder, AcctechSystemsVendorCustomizationUICallback.currencyCode, null, "Customization Currency Finder", sg.finderHelper.createDefaultFunction("txtCustomCurrency", "CurrencyCodeId", sg.finderOperator.StartsWith), null, true);
    },

    //Init CheckBoxs
    initCheckBoxes: function () {
    },

    //Init kendo Grid
    initGrid: function () {
    },

    //Init Other type controls
    initOtherControls: function () {
    },

};


var AcctechSystemsVendorCustomizationUICallback = {
};

// Initial Entry
$(function () {
    AcctechSystemsVendorCustomizationUI.init();
});
