//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage300JSCutomizationWFP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage300JSCutomizationWFP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///// This file was generated by a tool. 
        ///// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated. 
        ///
        /////declare ip address
        /////var ipAddress = &quot;10.1.0.4:1992&quot;
        ///var ipAddress = &quot;REPLACEME&quot;;
        /////get username + document number
        ///loggedInUser = Data_Invoices_EnteredBy.value;
        ///apDocNum = Data_Invoices_DocumentNumber.Data_Invoices_DocumentNumber.value;
        ///
        /////get live document number
        ///$(&quot;#txtInvHeadersDocumentNumber&quot;).keyup(function () {
        ///    apDocNum = Data_Invoices_DocumentN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string APInvoiceEntry_Customization {
            get {
                return ResourceManager.GetString("APInvoiceEntry_Customization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///// This file was generated by a tool. 
        ///// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated. 
        ///
        /////declare ip address
        /////var ipAddress = &quot;10.1.0.4:1992&quot;
        ///var ipAddress = &quot;REPLACEME&quot;;
        /////get username + document number
        ///loggedInUser = txtInvEnteredBy.value;
        ///arDocNum = txtInvHeadersDocumentNumber.value;
        ///
        /////get live document number
        ///$(&quot;#txtInvHeadersDocumentNumber&quot;).keyup(function () {
        ///    arDocNum = txtInvHeadersDocumentNumber.value;
        ///    arDocNum.toUpperCase( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ARInvoiceEntry_Customization {
            get {
                return ResourceManager.GetString("ARInvoiceEntry_Customization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///// This file was generated by a tool. 
        ///// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated. 
        ///
        ///// //declare ip address
        ///// //var ipAddress = &quot;10.1.0.4:1992&quot;
        ///var ipAddress = &quot;REPLACEME&quot;;
        ///// //get username + document number
        ///// loggedInUser = Data_Invoices_EnteredBy.value;
        ///apCustNum = Data_CustomerNumber.value;
        ///apCustNum = apCustNum.toUpperCase();
        ///
        /////get live document number
        ///$(&quot;#Data_CustomerNumber&quot;).keyup(function () {
        ///    apCustNum = Data_CustomerNumb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Customer_Customization {
            get {
                return ResourceManager.GetString("Customer_Customization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///// This file was generated by a tool. 
        ///// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated. 
        ///
        ///// //declare ip address
        ///// //var ipAddress = &quot;10.1.0.4:1992&quot;
        ///var ipAddress = &quot;REPLACEME&quot;;
        ///// //get username + document number
        ///// loggedInUser = Data_Invoices_EnteredBy.value;
        ///apVenNum = Data_VendorNumber.value;
        ///apVenNum = apVenNum.toUpperCase();
        ///
        /////get live document number
        ///$(&quot;#Data_VendorNumber&quot;).keyup(function () {
        ///    apVenNum = Data_VendorNumber.value;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vendor_Customization {
            get {
                return ResourceManager.GetString("Vendor_Customization", resourceCulture);
            }
        }
    }
}
